# Data Analysis

>Importing libraries

In [1]:
import pandas as pd
import numpy as np
import pandasql as ps
from pandasql import sqldf
import ast
import random
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import BayesianRidge
from sklearn import preprocessing
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

# Data Cleaning & Transformation

>Importing and viewing the fashion dataset


In [2]:
fashion_dataset= pd.read_csv(r".\fashion dataset.csv")
fashion_dataset

p_id                                               name   price  \
0       1518329.0   Dupatta Bazaar White Embroidered Chiffon Dupatta   899.0   
1       5829334.0  Roadster Women Mustard Yellow Solid Hooded Swe...  1199.0   
2      10340119.0  Inddus Peach-Coloured & Beige Unstitched Dress...  5799.0   
3      10856380.0            SASSAFRAS Women Black Parallel Trousers  1499.0   
4      12384822.0  Kotty Women Black Wide Leg High-Rise Clean Loo...  1999.0   
...           ...                                                ...     ...   
14324  17029604.0  The Chennai Silks Pink & Silver-Toned Floral Z...  3999.0   
14325  17600212.0  Kinder Kids Girls Blue & Green Printed Foil Pr...  2050.0   
14326  18159266.0  KLOTTHE Women Green & Black Floral Printed Pal...  1659.0   
14327  18921114.0             InWeave Women Red Printed A-Line Skirt  2399.0   
14328  19361058.0      BoStreet Women Navy Blue Tapered Fit Trousers  2599.0   

          colour              brand  ratingCount  avg_rating  \
0          White     Dupatta Bazaar       1321.0    4.548827   
1        Mustard           Roadster       5462.0    4.313255   
2          Peach             Inddus        145.0    4.068966   
3          Black          SASSAFRAS       9124.0    4.147523   
4          Black              Kotty      12260.0    4.078467   
...          ...                ...          ...         ...   
14324       Pink  The Chennai Silks          NaN         NaN   
14325       Blue        Kinder Kids          NaN         NaN   
14326      Green            KLOTTHE          NaN         NaN   
14327        Red            InWeave          NaN         NaN   
14328  Navy Blue           BoStreet          NaN         NaN   

                                             description  \
0      White embroidered&nbsp;dupattaChiffon<br>Hand-...   
1      Mustard yellow solid sweatshirt, has a hood, t...   
2      Peach-Coloured and beige woven design unstitch...   
3      Black solid woven high-rise parallel trousers,...   
4      Black dark wash 4-pocket high-rise jeans, clea...   
...                                                  ...   
14324  <b>Design Details </b><ul><li>Pink and silver-...   
14325  Blue and green printed lehenga choli,  has foi...   
14326  <ul> <li> Green and black woven palazzos </li>...   
14327  <p>Red printed A-line skirt, has drawstring cl...   
14328  <ul> <li> Navy blue knitted trousers </li> <li...   

                                            p_attributes  
0      {'Occasion': 'Daily', 'Pattern': 'Embroidered'...  
1      {'Body Shape ID': '443,424,324', 'Body or Garm...  
2      {'Bottom Fabric': 'Cotton Blend', 'Bottom Patt...  
3      {'Add-Ons': 'NA', 'Body Shape ID': '424', 'Bod...  
4      {'Add-Ons': 'NA', 'Brand Fit Name': 'NA', 'Clo...  
...                                                  ...  
14324  {'Better Cotton Initiative': 'Regular', 'Blous...  
14325  {'Blouse Closure': 'NA', 'Blouse Fabric': 'Cot...  
14326  {'Body or Garment Size': 'To-Fit Denotes Body ...  
14327  {'Add-Ons': 'NA', 'Body Shape ID': '324,333,42...  
14328  {'Add-Ons': 'NA', 'Body Shape ID': '443,333,42...  

[14329 rows x 9 columns]

>Finding the number of unique brands in the fashion dataset

In [3]:
len(pd.unique(fashion_dataset['brand']))

1021

>Importing the brand details dataset

In [4]:
brand_details = pd.read_excel(r".\fashion brand details.xlsx")
brand_details

brand_id    brand_name
0            1           513
1            2          109F
2            3     20Dresses
3            4   250 Designs
4            5          3Pin
...        ...           ...
1015      1016  Ziva Fashion
1016      1017        Zivame
1017      1018         Ziyaa
1018      1019        Zoella
1019      1020          Zola

[1020 rows x 2 columns]

>Counting the number of unique brand names in the brand details dataset

In [5]:
len(pd.unique(brand_details['brand_name']))

1020

>Finding the number of null and duplicated values in each dataset

In [6]:
brand_details.isna().sum()

brand_id      0
brand_name    0
dtype: int64

In [7]:
fashion_dataset.isna().sum()

p_id              18
name              19
price             19
colour            22
brand             24
ratingCount     7748
avg_rating      7748
description       19
p_attributes      19
dtype: int64

In [8]:
brand_details.duplicated().sum()

0

In [9]:
fashion_dataset.duplicated().sum()

59

>Testing out duplicate dropping

In [10]:
df_dupl = fashion_dataset.drop_duplicates(keep = "last")
len(pd.unique(df_dupl["brand"]))

1021

>Dropping duplicates in fashion dataset

In [11]:
fashion_dataset.drop_duplicates(inplace = True, keep = "last")
fashion_dataset

p_id                                               name   price  \
0       1518329.0   Dupatta Bazaar White Embroidered Chiffon Dupatta   899.0   
1       5829334.0  Roadster Women Mustard Yellow Solid Hooded Swe...  1199.0   
2      10340119.0  Inddus Peach-Coloured & Beige Unstitched Dress...  5799.0   
3      10856380.0            SASSAFRAS Women Black Parallel Trousers  1499.0   
4      12384822.0  Kotty Women Black Wide Leg High-Rise Clean Loo...  1999.0   
...           ...                                                ...     ...   
14324  17029604.0  The Chennai Silks Pink & Silver-Toned Floral Z...  3999.0   
14325  17600212.0  Kinder Kids Girls Blue & Green Printed Foil Pr...  2050.0   
14326  18159266.0  KLOTTHE Women Green & Black Floral Printed Pal...  1659.0   
14327  18921114.0             InWeave Women Red Printed A-Line Skirt  2399.0   
14328  19361058.0      BoStreet Women Navy Blue Tapered Fit Trousers  2599.0   

          colour              brand  ratingCount  avg_rating  \
0          White     Dupatta Bazaar       1321.0    4.548827   
1        Mustard           Roadster       5462.0    4.313255   
2          Peach             Inddus        145.0    4.068966   
3          Black          SASSAFRAS       9124.0    4.147523   
4          Black              Kotty      12260.0    4.078467   
...          ...                ...          ...         ...   
14324       Pink  The Chennai Silks          NaN         NaN   
14325       Blue        Kinder Kids          NaN         NaN   
14326      Green            KLOTTHE          NaN         NaN   
14327        Red            InWeave          NaN         NaN   
14328  Navy Blue           BoStreet          NaN         NaN   

                                             description  \
0      White embroidered&nbsp;dupattaChiffon<br>Hand-...   
1      Mustard yellow solid sweatshirt, has a hood, t...   
2      Peach-Coloured and beige woven design unstitch...   
3      Black solid woven high-rise parallel trousers,...   
4      Black dark wash 4-pocket high-rise jeans, clea...   
...                                                  ...   
14324  <b>Design Details </b><ul><li>Pink and silver-...   
14325  Blue and green printed lehenga choli,  has foi...   
14326  <ul> <li> Green and black woven palazzos </li>...   
14327  <p>Red printed A-line skirt, has drawstring cl...   
14328  <ul> <li> Navy blue knitted trousers </li> <li...   

                                            p_attributes  
0      {'Occasion': 'Daily', 'Pattern': 'Embroidered'...  
1      {'Body Shape ID': '443,424,324', 'Body or Garm...  
2      {'Bottom Fabric': 'Cotton Blend', 'Bottom Patt...  
3      {'Add-Ons': 'NA', 'Body Shape ID': '424', 'Bod...  
4      {'Add-Ons': 'NA', 'Brand Fit Name': 'NA', 'Clo...  
...                                                  ...  
14324  {'Better Cotton Initiative': 'Regular', 'Blous...  
14325  {'Blouse Closure': 'NA', 'Blouse Fabric': 'Cot...  
14326  {'Body or Garment Size': 'To-Fit Denotes Body ...  
14327  {'Add-Ons': 'NA', 'Body Shape ID': '324,333,42...  
14328  {'Add-Ons': 'NA', 'Body Shape ID': '443,333,42...  

[14270 rows x 9 columns]

> Expanding the p_attributes column


In [12]:
fashion_dataset['p_attributes'] = fashion_dataset['p_attributes']
not_null = pd.notnull(fashion_dataset['p_attributes'])
fash3 = fashion_dataset[not_null]['p_attributes'].apply(lambda x: ast.literal_eval(x))
temp = pd.DataFrame([*fash3], fash3.index)
fashion_dataset = pd.concat([fashion_dataset, temp], axis=1)

>Viewing all columns of the dataset

In [13]:
print(list(fashion_dataset.columns))

['p_id', 'name', 'price', 'colour', 'brand', 'ratingCount', 'avg_rating', 'description', 'p_attributes', 'Occasion', 'Pattern', 'Print or Pattern Type', 'Body Shape ID', 'Body or Garment Size', 'Closure', 'Fabric', 'Hemline', 'Hood', 'Length', 'Neck', 'Number of Pockets', 'Pocket', 'Sleeve Length', 'Surface Styling', 'Type', 'Wash Care', 'Bottom Fabric', 'Bottom Pattern', 'Dupatta Border', 'Dupatta Fabric', 'Dupatta Pattern', 'Kurta Fabric', 'Kurta Pattern', 'Ornamentation', 'Set Content', 'Stitch', 'Technique', 'Add-Ons', 'Brand Fit Name', 'Character', 'Fabric 2', 'Features', 'Fit', 'Fly Type', 'Main Trend', 'Multipack Set', 'Sustainable', 'Type of Pleat', 'Waist Rise', 'Weave Type', 'Distress', 'Effects', 'Fabric 3', 'Fade', 'Reversible', 'Shade', 'Stretch', 'Type of Distress', 'Waistband', 'Center Front Open', 'Fabric Type', 'Lining', 'Sleeve Styling', 'Transparency', 'taxMaterial', 'Front Styling', 'Knit or Woven', 'Sport', 'Technology', 'Blouse Closure', 'Blouse Fabric', 'Choli St

>Renaming columns for use in SQL and MapReduce

In [14]:
fashion_dataset.rename(columns={'Where-to-wear':'Where_to_wear','Dupatta Pattern':'Dupatta_Pattern', 'Kurta Pattern':'Kurta_Pattern','Bottom Pattern': 'Bottom_Pattern', 'Top Pattern': 'Top_Pattern','Print or Pattern Type': 'Print_Pattern_Type', 'Knit or Woven':'Knit_or_Woven', 'Weave Type':'Weave_Type', 'Weave Pattern':'Weave_Pattern','Dupatta Fabric':'Dupatta_Fabric','Bottom Fabric':'Bottom_Fabric', 'Top Fabric':'Top_Fabric','Fabric Purity':'Fabric_Purity', 'Fabric Type':'Fabric_Type','Blouse Fabric':'Blouse_Fabric', 'Better Cotton Initiative':'Better_Cotton', 'Saree Fabric':'Saree_Fabric', 'Colour Family':'Colour_Family'}, inplace=True)

In [15]:
fashion_dataset['Kurta_Pattern'].isna().sum()

13657

In [16]:
fashion_dataset['Weave_Type'].isna().sum()

8923

In [17]:
fashion_dataset['Knit_or_Woven'].isna().sum()

12353

In [18]:
fashion_dataset['Weave_Pattern'].isna().sum()

13087

### Filling the Fabric column

In [19]:
pd.unique(fashion_dataset['Fabric'])

array([nan, 'Cotton', 'Polyester', 'Poly Crepe', 'Polyviscose',
       'Viscose Rayon', 'Wool', 'Pure Cotton', 'Cotton Blend',
       'Poly Chiffon', 'Linen', 'Poly Georgette', 'Georgette',
       'Silk Blend', 'Fleece', 'Net', 'Modal', 'Art Silk', 'Acrylic',
       'Other', 'Polycotton', 'Nylon', 'Denim', 'Leather', 'Velvet',
       'Liva', 'Poly Silk', 'Silk', 'Pure Silk', 'PU', 'Cotton Silk',
       'Corduroy', 'Organza', 'Viscose Georgette', 'Wool Blend',
       'Chiffon', 'Organic Cotton', 'Brocade', 'Faux Fur', 'Suede',
       'Satin', 'Pure Georgette', 'Chanderi Silk', 'Crepe', 'Tencel',
       'Elastane', 'Dupion', 'Jacquard', 'Synthetic Leather', 'Voile',
       'Dupion Silk', 'Velour', 'Pashmina', 'Pure Crepe', 'Lyocell',
       'Raw Silk', 'Polyester PU Coated', 'Hemp', 'Livaeco'], dtype=object)

In [20]:
sqldf("select count(Fabric) from fashion_dataset where Fabric = 'NA'")

count(Fabric)
0              0

In [21]:
fashion_dataset['Fabric'].isna().sum()

3882

In [22]:
pd.unique(fashion_dataset['Bottom_Fabric'])

array([nan, 'Cotton Blend', 'Viscose Rayon', 'Pure Cotton', 'Satin',
       'Polyester', 'Poly Georgette', 'Shantoon', 'Silk Georgette',
       'Poly Crepe', 'Organic Cotton', 'Poly Silk', 'Silk Blend',
       'Art Silk', 'Pure Silk', 'Pure Wool', 'Poly Chiffon', 'Net',
       'Silk Crepe', 'Silk Chiffon', 'Linen', 'NA', 'Pashmina',
       'Jute Cotton', 'Nylon', 'Velvet', 'Voile'], dtype=object)

In [23]:
fashion_dataset['Bottom_Fabric'] = fashion_dataset['Bottom_Fabric'].where(fashion_dataset['Bottom_Fabric'] != 'NA', None)

In [24]:
pd.unique(fashion_dataset['Blouse_Fabric'])

array([nan, 'Viscose Rayon', 'Organza', 'Poly Silk', 'Silk Blend',
       'Cotton', 'Linen Blend', 'Poly Georgette', 'Pure Georgette',
       'Art Silk', 'Net', 'Silk', 'Satin', 'NA', 'Pure Silk', 'Polyester',
       'Brocade', 'Tissue', 'Cotton Blend', 'Silk Cotton', 'Velvet',
       'Poly Crepe', 'Pure Cotton', 'Raw Silk', 'Polycotton',
       'Pure Chiffon', 'Jute Silk', 'Poly Chiffon', 'Liva', 'Pure Crepe',
       'Pure Linen', 'Supernet', 'Jute Cotton'], dtype=object)

In [25]:
fashion_dataset['Blouse_Fabric'] = fashion_dataset['Blouse_Fabric'].where(fashion_dataset['Blouse_Fabric'] != 'NA', None)

In [26]:
pd.unique(fashion_dataset['Top_Fabric'])

array([nan, 'Cotton Blend', 'Viscose Rayon', 'Pure Cotton', 'Polyester',
       'Liva', 'Poly Crepe', 'Organic Cotton', 'Poly Silk', 'Silk Blend',
       'Poly Georgette', 'Art Silk', 'Pure Wool', 'Net', 'Silk Chiffon',
       'Linen', 'Poly Chanderi', 'Pure Silk', 'Chanderi Cotton',
       'Chanderi Silk', 'Acrylic', 'Silk Georgette', 'Nylon', 'Velvet',
       'Poly Chiffon', 'Voile'], dtype=object)

In [27]:
pd.unique(fashion_dataset['Fabric_Type'])

array([nan, 'Georgette', 'NA', 'Denim', 'Cotton', 'Lace', 'Crepe',
       'Chiffon', 'Cotton Cambric', 'Net', 'Dobby', 'Scuba', 'Satin',
       'Liva', 'Twill', 'Linen', 'Chambray', 'Velvet', 'Jacquard',
       'Corduroy', 'Schiffli', 'Terry'], dtype=object)

In [28]:
fashion_dataset['Fabric_Type'] = fashion_dataset['Fabric_Type'].where(fashion_dataset['Fabric_Type'] != 'NA', None)

In [29]:
fashion_dataset['Fabric'] = fashion_dataset['Fabric'].combine_first(fashion_dataset['Top_Fabric'])

In [30]:
fashion_dataset['Fabric'].isna().sum()

2708

In [31]:
fashion_dataset['Fabric'] = fashion_dataset['Fabric'].combine_first(fashion_dataset['Bottom_Fabric'])

In [32]:
fashion_dataset['Fabric'].isna().sum()

2076

In [33]:
fashion_dataset['Fabric'] = fashion_dataset['Fabric'].combine_first(fashion_dataset['Fabric_Type'])

In [34]:
fashion_dataset['Fabric'].isna().sum()

2025

In [35]:
fashion_dataset['Fabric'] = fashion_dataset['Fabric'].combine_first(fashion_dataset['Blouse_Fabric'])

In [36]:
fashion_dataset['Fabric'].isna().sum()

202

In [37]:
pd.unique(fashion_dataset['Better_Cotton'])

array([nan, 'Regular', 'Better Cotton Initiative'], dtype=object)

In [38]:
sqldf("select Better_Cotton from fashion_dataset where Fabric is null and Better_Cotton in('Better Cotton Initiative','Regular')")

Better_Cotton
0       Regular
1       Regular
2       Regular

In [39]:
fashion_dataset['New_Cotton'] = fashion_dataset['Better_Cotton'].replace(['Regular', 'Better Cotton Initiative'], ['Cotton',None])

In [40]:
fashion_dataset['Fabric'] = fashion_dataset['Fabric'].combine_first(fashion_dataset['New_Cotton'])

In [41]:
fashion_dataset['Fabric'].isna().sum()

199

In [42]:
pd.unique(fashion_dataset['Dupatta_Fabric'])
fashion_dataset['Dupatta_Fabric'] = fashion_dataset['Dupatta_Fabric'].where(fashion_dataset['Dupatta_Fabric'] != 'NA', None)

In [43]:
sqldf("select Dupatta_Fabric from fashion_dataset where Dupatta_Fabric is not null and Fabric is null")

Dupatta_Fabric
0            Net

In [44]:
sqldf("select Weave_Pattern, Fabric from fashion_dataset")

Weave_Pattern         Fabric
0              None           None
1              None         Cotton
2              None   Cotton Blend
3              None           None
4              None         Cotton
...             ...            ...
14265          None    Jute Cotton
14266          None         Cotton
14267          None     Polycotton
14268          None  Viscose Rayon
14269          None          Nylon

[14270 rows x 2 columns]

In [45]:
fashion_dataset['Fabric'] = fashion_dataset['Fabric'].combine_first(fashion_dataset['Weave_Pattern'])

In [46]:
fashion_dataset['Fabric'] = fashion_dataset['Fabric'].combine_first(fashion_dataset['Dupatta_Fabric'])

In [47]:
fashion_dataset['Fabric'].isna().sum()

197

In [48]:
sqldf("select Saree_Fabric from fashion_dataset where Saree_Fabric is not null and Fabric is null")

Saree_Fabric
0   Poly Georgette
1       Pure Linen
2      Pure Cotton
3     Cotton Blend
4     Cotton Blend
5       Pure Linen
6      Pure Cotton
7     Pure Chiffon
8     Poly Chiffon
9      Pure Cotton
10     Pure Cotton
11    Pure Chiffon
12     Pure Cotton
13         Organza
14    Cotton Blend
15      Polycotton
16      Polycotton
17     Pure Cotton
18      Pure Linen
19    Cotton Blend
20    Cotton Blend
21           Satin
22    Pure Chiffon
23         Organza
24       Polyester
25     Pure Cotton
26            Liva
27     Pure Cotton
28    Cotton Blend
29     Pure Cotton
30     Pure Cotton
31     Pure Cotton
32           Satin
33           Satin
34     Pure Cotton
35     Pure Cotton
36     Silk Cotton
37     Silk Cotton
38     Pure Cotton
39    Cotton Blend
40           Satin
41    Poly Chiffon
42           Nylon
43     Pure Cotton
44     Pure Cotton
45    Pure Chiffon
46    Cotton Blend
47     Pure Cotton
48    Cotton Blend
49     Pure Cotton
50     Pure Cotton
51    Pure Chiffon
52     Pure Cotton
53    Cotton Blend
54     Pure Cotton

In [49]:
fashion_dataset['Fabric'] = fashion_dataset['Fabric'].combine_first(fashion_dataset['Saree_Fabric'])

In [50]:
fashion_dataset['Fabric'].isna().sum()

142

In [51]:
fashion_dataset['Fabric'].mode()

0    Cotton
Name: Fabric, dtype: object

In [52]:
fashion_dataset.fillna({'Fabric':'Cotton'}, inplace=True)
fashion_dataset['Fabric'].isna().sum()

0

In [53]:
sqldf("select count(Fabric) from fashion_dataset where Fabric = 'NA'")

count(Fabric)
0              0

### Viewing Weave Type & Knit or Woven

In [54]:
pd.unique(fashion_dataset['Weave_Type'])

array([nan, 'Woven', 'Machine Weave', 'Knitted', 'Knitted and Woven',
       'Velvet', 'Denim', 'Handloom', 'Lace', 'Chambray', 'Corduroy'],
      dtype=object)

In [55]:
pd.unique(fashion_dataset['Weave_Type'])

array([nan, 'Woven', 'Machine Weave', 'Knitted', 'Knitted and Woven',
       'Velvet', 'Denim', 'Handloom', 'Lace', 'Chambray', 'Corduroy'],
      dtype=object)

In [56]:
pd.unique(fashion_dataset['Knit_or_Woven'])

array([nan, 'Knitted', 'Knitted and Woven', 'Woven'], dtype=object)

In [57]:
pd.unique(fashion_dataset['Weave_Pattern'])

array([nan, 'Regular', 'Jacquard', 'Brocade', 'Dobby', 'Khadi'],
      dtype=object)

### Formatting Weave Pattern  and Weave Type to fill Knit or Woven

In [58]:
fashion_dataset['Weave_Pattern_2'] = fashion_dataset['Weave_Pattern'].replace(['Regular', 'Jacquard', 'Brocade', 'Dobby', 'Khadi'], ['Woven','Woven','Woven','Woven','Woven'])

In [59]:
pd.unique(fashion_dataset['Weave_Pattern_2'])

array([nan, 'Woven'], dtype=object)

In [60]:
fashion_dataset['Weave_Type_2'] = fashion_dataset['Weave_Type'].replace(['Machine Weave',
       'Velvet', 'Denim', 'Handloom', 'Lace', 'Chambray', 'Corduroy'], ['Woven','Woven','Woven','Woven','Knitted','Woven','Woven'])

In [61]:
pd.unique(fashion_dataset['Weave_Type_2'])

array([nan, 'Woven', 'Knitted', 'Knitted and Woven'], dtype=object)

### Filling Knit_or_Woven

In [62]:
fashion_dataset['Knit_or_Woven'] = fashion_dataset['Knit_or_Woven'].combine_first(fashion_dataset['Weave_Pattern_2'])

In [63]:
fashion_dataset['Knit_or_Woven'] = fashion_dataset['Knit_or_Woven'].combine_first(fashion_dataset['Weave_Type_2'])

In [64]:
fashion_dataset['Knit_or_Woven'].isna().sum()

7006

In [65]:
pd.unique(fashion_dataset['Knit_or_Woven'])

array([nan, 'Woven', 'Knitted', 'Knitted and Woven'], dtype=object)

In [66]:
len(pd.unique(fashion_dataset['Fabric']))

75

In [67]:
fabrics_knit = sqldf("select distinct Fabric from fashion_dataset where Knit_or_Woven = 'Knitted'")

In [68]:
fabrics_knit.isna().sum()

Fabric    0
dtype: int64

In [69]:
fabrics_weave = sqldf("select distinct Fabric from fashion_dataset where Knit_or_Woven = 'Woven'")

In [70]:
fabrics_weave.isna().sum()

Fabric    0
dtype: int64

In [71]:
fabrics_both = sqldf("select distinct Fabric from fashion_dataset where Knit_or_Woven = 'Knitted and Woven'")

In [72]:
fabrics_both.isna().sum()

Fabric    0
dtype: int64

In [73]:
knit_n_woven = sqldf("select * from fabrics_knit where fabrics_knit.Fabric in(select fabrics_weave.Fabric from fabrics_weave)")

In [74]:
knit_n_woven = sqldf("select * from knit_n_woven where Fabric not in ('Other')")
knit_n_woven

Fabric
0           Cotton
1        Polyester
2            Denim
3      Pure Cotton
4     Cotton Blend
5    Viscose Rayon
6           Fleece
7          Acrylic
8            Linen
9            Nylon
10            Wool
11              PU
12      Silk Blend
13           Modal
14      Polycotton
15  Organic Cotton
16       Georgette
17           Satin
18            Silk
19        Jacquard
20           Suede
21            Liva
22        Corduroy

In [75]:
fabrics_both = sqldf("select * from fabrics_both where Fabric not in (select Fabric from knit_n_woven)")

In [76]:
both_fabrics = ps.sqldf("select * from knit_n_woven union all select * from fabrics_both")

In [77]:
both_fabrics.loc[:,'weave'] = 'Knitted and Woven'

In [78]:
fabrics_knit = sqldf("select * from fabrics_knit where Fabric not in (select Fabric from both_fabrics) and Fabric != 'Other'")
fabrics_knit.loc[:,['weave']]='Knitted'

In [79]:
fabrics_knit

Fabric    weave
0   Scuba  Knitted
1  Velour  Knitted

In [80]:
fabrics_weave = sqldf("select * from fabrics_weave where Fabric not in (select Fabric from both_fabrics) and Fabric != 'Other'")
fabrics_weave.loc[:,['weave']]='Woven'

In [81]:
fabrics_weave

Fabric  weave
0          Poly Crepe  Woven
1               Crepe  Woven
2           Poly Silk  Woven
3      Poly Georgette  Woven
4            Art Silk  Woven
5             Leather  Woven
6             Regular  Woven
7                 Net  Woven
8        Silk Chiffon  Woven
9         Cotton Silk  Woven
10             Velvet  Woven
11      Poly Chanderi  Woven
12          Pure Silk  Woven
13            Chiffon  Woven
14    Chanderi Cotton  Woven
15           Faux Fur  Woven
16     Pure Georgette  Woven
17      Chanderi Silk  Woven
18  Synthetic Leather  Woven
19     Silk Georgette  Woven
20        Dupion Silk  Woven
21         Pure Crepe  Woven
22       Poly Chiffon  Woven
23              Voile  Woven
24               Hemp  Woven
25            Livaeco  Woven

In [82]:
fabric_weave_type = sqldf("select * from fabrics_weave union all select * from fabrics_knit union all select * from both_fabrics")
fabric_weave_type

Fabric              weave
0            Poly Crepe              Woven
1                 Crepe              Woven
2             Poly Silk              Woven
3        Poly Georgette              Woven
4              Art Silk              Woven
5               Leather              Woven
6               Regular              Woven
7                   Net              Woven
8          Silk Chiffon              Woven
9           Cotton Silk              Woven
10               Velvet              Woven
11        Poly Chanderi              Woven
12            Pure Silk              Woven
13              Chiffon              Woven
14      Chanderi Cotton              Woven
15             Faux Fur              Woven
16       Pure Georgette              Woven
17        Chanderi Silk              Woven
18    Synthetic Leather              Woven
19       Silk Georgette              Woven
20          Dupion Silk              Woven
21           Pure Crepe              Woven
22         Poly Chiffon              Woven
23                Voile              Woven
24                 Hemp              Woven
25              Livaeco              Woven
26                Scuba            Knitted
27               Velour            Knitted
28               Cotton  Knitted and Woven
29            Polyester  Knitted and Woven
30                Denim  Knitted and Woven
31          Pure Cotton  Knitted and Woven
32         Cotton Blend  Knitted and Woven
33        Viscose Rayon  Knitted and Woven
34               Fleece  Knitted and Woven
35              Acrylic  Knitted and Woven
36                Linen  Knitted and Woven
37                Nylon  Knitted and Woven
38                 Wool  Knitted and Woven
39                   PU  Knitted and Woven
40           Silk Blend  Knitted and Woven
41                Modal  Knitted and Woven
42           Polycotton  Knitted and Woven
43       Organic Cotton  Knitted and Woven
44            Georgette  Knitted and Woven
45                Satin  Knitted and Woven
46                 Silk  Knitted and Woven
47             Jacquard  Knitted and Woven
48                Suede  Knitted and Woven
49                 Liva  Knitted and Woven
50             Corduroy  Knitted and Woven
51  Polyester PU Coated  Knitted and Woven

In [83]:
fashion_dataset = sqldf("select fashion_dataset.*, fabric_weave_type.weave from fashion_dataset left join fabric_weave_type on (fabric_weave_type.Fabric=fashion_dataset.Fabric)")

In [84]:
fashion_dataset['Knit_or_Woven'] = fashion_dataset['Knit_or_Woven'].combine_first(fashion_dataset['weave'])

In [85]:
fashion_dataset['Knit_or_Woven'].isna().sum()

509

### Filling Occasion

In [97]:
fashion_dataset['Occasion'].isna().sum()

1047

In [86]:
pd.unique(fashion_dataset['Occasion'])

array(['Daily', 'Casual', None, 'Party', 'Festive', 'Formal', 'Ethnic',
       'Fusion', 'Traditional', 'Western', 'Sports', 'Work', 'Outdoor',
       'Maternity'], dtype=object)

In [87]:
pd.unique(fashion_dataset['Where_to_wear'])

array([None, 'Look a cut above the rest at wedding festivities',
       'Ideal for daily or office wear', 'Fun weekends with friends',
       "Look stylish at your bestie's wedding party",
       'A weekend escape with friends',
       'A graceful look for a small family function',
       'Wedding, Party, Engagement, Reception, Haldi, Mehandi Occasion',
       'Wear it to a fun weekend party', 'Wedding',
       "Enjoy your sister's housewarming",
       'This Lengha Choli Set Can Be wear at Home For Small Function ,Get Together ,At Different Festivals &amp; In Party .',
       'Wear to fun destination weddings',
       'Casual, parties, regular, holiays, night out, work wear, formal, holidays',
       'Ideal to wear to a high-tea party with friends',
       'Ideal for a Saturday night outing', '',
       'Look gorgeous driving down to the beach',
       "Ideal for spending a relaxed day at your friend's wedding festivities",
       'Casual Fridays at work or lunch with friends',
      

In [88]:
where_to = sqldf("select Where_to_wear, Occasion from fashion_dataset where Occasion is not null and Where_to_wear is not null")
where_to

Where_to_wear Occasion
0                 Ideal for daily or office wear    Party
1                      Fun weekends with friends   Casual
2                  A weekend escape with friends   Casual
3    A graceful look for a small family function    Party
4                 Wear it to a fun weekend party   Casual
..                                           ...      ...
674             Ideal for a festive get-together    Party
675           Ideal for a visit to a coffee shop   Casual
676                     Look beautiful at a roka    Party
677                      Jazz up a festive party  Festive
678                Perfect for any family outing   Casual

[679 rows x 2 columns]

In [89]:
wear = sqldf("select distinct Where_to_wear from fashion_dataset where Occasion is not null")
wear

Where_to_wear
0                                                 None
1                       Ideal for daily or office wear
2                            Fun weekends with friends
3                        A weekend escape with friends
4          A graceful look for a small family function
..                                                 ...
353                                     office, dayout
354  Wrap Up The Look With A Pair Of Slippers, Sand...
355              Ideal for an outing with your besties
356                           Look beautiful at a roka
357                            Jazz up a festive party

[358 rows x 1 columns]

In [90]:
#wear = sqldf("select wear.*, where_to.Occasion from wear join where_to on (wear.Where_to_wear=where_to.Where_to_wear)")

In [91]:
wear.duplicated().sum()

0

In [92]:
wear.loc[:,['occasion']]=where_to['Occasion']
pd.unique(wear['occasion'])
wear.isna().sum()

Where_to_wear    1
occasion         0
dtype: int64

In [94]:
fashion_dataset = sqldf("select fashion_dataset.*, wear.* from fashion_dataset left join wear on (wear.Where_to_wear=fashion_dataset.Where_to_wear)")

In [95]:
fashion_dataset['Occasion'] = fashion_dataset['Occasion'].combine_first(fashion_dataset['occasion'])

In [96]:
fashion_dataset['Occasion'].isna().sum()

1047